DELETE FROM USER_ROLE;
DELETE FROM ATTACHMENT;
DELETE FROM BUG;
DELETE FROM ROLE_PERMISSION;
DELETE FROM PERMISSION;
DELETE FROM ROLE;
DELETE FROM USER;
INSERT INTO USER(USERNAME, FIRSTNAME, LASTNAME, PASSWORD,ACTIVE, EMAIL, LOCKVERSION,NUMBEROFTRIES,PHONENUMBER) VALUES ('SmithS','Samantha','Smith','pass','1', 'samy_smith@msggroup.com','1','0','+40747567350');
INSERT INTO USER(USERNAME, FIRSTNAME, LASTNAME, PASSWORD,ACTIVE, EMAIL, LOCKVERSION,NUMBEROFTRIES,PHONENUMBER) VALUES ('SmithJ','John','Smith','pass','0', 'john_smith@msggroup.com','1','0','+40747567350');
INSERT INTO USER(USERNAME, FIRSTNAME, LASTNAME, PASSWORD,ACTIVE, EMAIL, LOCKVERSION,NUMBEROFTRIES,PHONENUMBER) VALUES ('SmithM','Mary','Smith','pass','1', 'mary_smith@msggroup.com','1','0','+40747567350');
INSERT INTO USER(USERNAME, FIRSTNAME, LASTNAME, PASSWORD,ACTIVE, EMAIL, LOCKVERSION,NUMBEROFTRIES,PHONENUMBER) VALUES ('SmithK','Kitty','Smith','pass','1', 'kitty_smith@msggroup.com','1','0','+40747567350');

INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION, LOCKVERSION) VALUES ('BUG_MANAGEMENT','', 1);
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION, LOCKVERSION) VALUES ('PERMISSION_MANAGEMENT','', 1);
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION, LOCKVERSION) VALUES ('USER_MANAGEMENT','', 1);
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION, LOCKVERSION) VALUES ('BUG_CLOSE','', 1);
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION, LOCKVERSION) VALUES ('BUG_EXPORT_PDF','', 1);

INSERT INTO ROLE(ROLENAME, LOCKVERSION) VALUES('ADMINISTRATOR', 1);
INSERT INTO ROLE(ROLENAME, LOCKVERSION) VALUES('PROJECT_MANAGER', 1);
INSERT INTO ROLE(ROLENAME, LOCKVERSION) VALUES('TEST_MANAGER', 1);
INSERT INTO ROLE(ROLENAME, LOCKVERSION) VALUES('DEVELOPER', 1);
INSERT INTO ROLE(ROLENAME, LOCKVERSION) VALUES('TESTER', 1);

INSERT INTO USER_ROLE(IDUSER, IDROLE) VALUES(1,1);
INSERT INTO USER_ROLE(IDUSER, IDROLE) VALUES(2,2);
INSERT INTO USER_ROLE(IDUSER, IDROLE) VALUES(3,2);
INSERT INTO USER_ROLE(IDUSER, IDROLE) VALUES(4,3);

INSERT INTO ROLE_PERMISSION VALUES(1,4);
INSERT INTO ROLE_PERMISSION VALUES(2,3);
INSERT INTO ROLE_PERMISSION VALUES(3,5);
INSERT INTO ROLE_PERMISSION VALUES(4,2);
INSERT INTO ROLE_PERMISSION VALUES(2,1);
INSERT INTO ROLE_PERMISSION VALUES(3,4);
INSERT INTO ROLE_PERMISSION VALUES(4,3);
INSERT INTO ROLE_PERMISSION VALUES(1,5);
INSERT INTO ROLE_PERMISSION VALUES(2,2);
INSERT INTO ROLE_PERMISSION VALUES(3,1);