
--INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Max', 'Mustermann');
--INSERT INTO USER (FIRSTNAME, LASTNAME) VALUES ('Mary', 'Jane');
DELETE FROM PERMISSION;
DELETE FROM ROLE;
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION) VALUES ('BUG_MANAGMENT','');
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION) VALUES ('PERMISSION_MANAGMENT','');
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION) VALUES ('USER_MANAGMENT','');
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION) VALUES ('BUG_CLOSE','');
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION) VALUES ('BUG_EXPORT_PDF','');
INSERT INTO PERMISSION(NAMEPERMISSION,DETAILPERMISSION) VALUES ('USERUL_ADRESAT','');

INSERT INTO ROLE(ROLENAME) VALUES('ADMINISTRATOR');
INSERT INTO ROLE(ROLENAME) VALUES('PROJECT MANAGER');
INSERT INTO ROLE(ROLENAME) VALUES('TEST MANAGER');
INSERT INTO ROLE(ROLENAME) VALUES('DEVELOPER');
INSERT INTO ROLE(ROLENAME) VALUES('TESTER');
