-- User test data

INSERT INTO USER (PASSWORD, USERNAME) VALUES ('pass', 'user11');
INSERT INTO USER (ACTIVE,EMAIL,FIRSTNAME,LASTNAME,LOCKVERSION, PASSWORD,PHONENUMBER, USERNAME) VALUES ('1' , 'maxmu@msggroup.com','Max','Mustermann','100','pass','0740829512','maxmus');
INSERT INTO USER (ACTIVE,EMAIL,FIRSTNAME,LASTNAME,LOCKVERSION, PASSWORD,PHONENUMBER, USERNAME) VALUES ('0' , 'janem@msggroup.com','Mary','Jane','101','pass','0756691512','maryja');